// Extended types for GradNet features matching comprehensive database schema
// These complement the existing types.ts file

export interface GradNetDatabase {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          role: 'applicant' | 'mentor' | 'admin' | 'university_rep' | 'consultant' | 'super_admin';
          full_name: string;
          display_name: string | null;
          bio: string | null;
          profile_picture_url: string | null;
          cover_photo_url: string | null;
          location: string | null;
          timezone: string;
          date_of_birth: string | null;
          nationality: string | null;
          email: string | null;
          phone: string | null;
          alternate_email: string | null;
          linkedin_url: string | null;
          website_url: string | null;
          github_url: string | null;
          twitter_url: string | null;
          orcid_id: string | null;
          google_scholar_url: string | null;
          researchgate_url: string | null;
          email_notifications: boolean;
          push_notifications: boolean;
          sms_notifications: boolean;
          profile_visibility: 'public' | 'private' | 'connections';
          search_visibility: boolean;
          language_preference: string;
          theme_preference: string;
          notification_frequency: string;
          is_verified: boolean;
          verification_status: 'unverified' | 'pending' | 'verified' | 'rejected';
          verification_documents: any[];
          verification_notes: string | null;
          last_active_at: string;
          onboarding_completed: boolean;
          onboarding_step: number;
          profile_completion_percentage: number;
          two_factor_enabled: boolean;
          account_locked: boolean;
          login_attempts: number;
          last_password_change: string | null;
          privacy_settings: any;
          total_posts: number;
          total_comments: number;
          total_likes: number;
          reputation_score: number;
          created_at: string;
          updated_at: string;
          last_login: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          role?: 'applicant' | 'mentor' | 'admin' | 'university_rep' | 'consultant' | 'super_admin';
          full_name: string;
          display_name?: string | null;
          bio?: string | null;
          profile_picture_url?: string | null;
          cover_photo_url?: string | null;
          location?: string | null;
          timezone?: string;
          date_of_birth?: string | null;
          nationality?: string | null;
          email?: string | null;
          phone?: string | null;
          alternate_email?: string | null;
          linkedin_url?: string | null;
          website_url?: string | null;
          github_url?: string | null;
          twitter_url?: string | null;
          orcid_id?: string | null;
          google_scholar_url?: string | null;
          researchgate_url?: string | null;
          email_notifications?: boolean;
          push_notifications?: boolean;
          sms_notifications?: boolean;
          profile_visibility?: 'public' | 'private' | 'connections';
          search_visibility?: boolean;
          language_preference?: string;
          theme_preference?: string;
          notification_frequency?: string;
          is_verified?: boolean;
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected';
          verification_documents?: any[];
          verification_notes?: string | null;
          last_active_at?: string;
          onboarding_completed?: boolean;
          onboarding_step?: number;
          profile_completion_percentage?: number;
          two_factor_enabled?: boolean;
          account_locked?: boolean;
          login_attempts?: number;
          last_password_change?: string | null;
          privacy_settings?: any;
          total_posts?: number;
          total_comments?: number;
          total_likes?: number;
          reputation_score?: number;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: 'applicant' | 'mentor' | 'admin' | 'university_rep' | 'consultant' | 'super_admin';
          full_name?: string;
          display_name?: string | null;
          bio?: string | null;
          profile_picture_url?: string | null;
          cover_photo_url?: string | null;
          location?: string | null;
          timezone?: string;
          date_of_birth?: string | null;
          nationality?: string | null;
          email?: string | null;
          phone?: string | null;
          alternate_email?: string | null;
          linkedin_url?: string | null;
          website_url?: string | null;
          github_url?: string | null;
          twitter_url?: string | null;
          orcid_id?: string | null;
          google_scholar_url?: string | null;
          researchgate_url?: string | null;
          email_notifications?: boolean;
          push_notifications?: boolean;
          sms_notifications?: boolean;
          profile_visibility?: 'public' | 'private' | 'connections';
          search_visibility?: boolean;
          language_preference?: string;
          theme_preference?: string;
          notification_frequency?: string;
          is_verified?: boolean;
          verification_status?: 'unverified' | 'pending' | 'verified' | 'rejected';
          verification_documents?: any[];
          verification_notes?: string | null;
          last_active_at?: string;
          onboarding_completed?: boolean;
          onboarding_step?: number;
          profile_completion_percentage?: number;
          two_factor_enabled?: boolean;
          account_locked?: boolean;
          login_attempts?: number;
          last_password_change?: string | null;
          privacy_settings?: any;
          total_posts?: number;
          total_comments?: number;
          total_likes?: number;
          reputation_score?: number;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
        };
      };
      gradnet_posts: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          content: string;
          post_type: 'general' | 'question' | 'resource' | 'achievement' | 'announcement' | 'discussion' | 'job_posting' | 'study_group' | 'mentor_request' | 'success_story';
          media_urls: string[] | null;
          media_types: string[] | null;
          media_captions: string[] | null;
          tags: string[] | null;
          categories: string[] | null;
          university_tags: string[] | null;
          program_tags: string[] | null;
          visibility: 'public' | 'private' | 'connections' | 'mentors';
          allowed_viewers: string[] | null;
          comments_enabled: boolean;
          sharing_enabled: boolean;
          like_count: number;
          comment_count: number;
          share_count: number;
          view_count: number;
          is_flagged: boolean;
          flag_reason: string | null;
          is_approved: boolean;
          moderated_by: string | null;
          moderated_at: string | null;
          is_scheduled: boolean;
          scheduled_for: string | null;
          is_pinned: boolean;
          is_archived: boolean;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          last_activity: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          content: string;
          post_type?: 'general' | 'question' | 'resource' | 'achievement' | 'announcement' | 'discussion' | 'job_posting' | 'study_group' | 'mentor_request' | 'success_story';
          media_urls?: string[] | null;
          media_types?: string[] | null;
          media_captions?: string[] | null;
          tags?: string[] | null;
          categories?: string[] | null;
          university_tags?: string[] | null;
          program_tags?: string[] | null;
          visibility?: 'public' | 'private' | 'connections' | 'mentors';
          allowed_viewers?: string[] | null;
          comments_enabled?: boolean;
          sharing_enabled?: boolean;
          like_count?: number;
          comment_count?: number;
          share_count?: number;
          view_count?: number;
          is_flagged?: boolean;
          flag_reason?: string | null;
          is_approved?: boolean;
          moderated_by?: string | null;
          moderated_at?: string | null;
          is_scheduled?: boolean;
          scheduled_for?: string | null;
          is_pinned?: boolean;
          is_archived?: boolean;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          last_activity?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string | null;
          content?: string;
          post_type?: 'general' | 'question' | 'resource' | 'achievement' | 'announcement' | 'discussion' | 'job_posting' | 'study_group' | 'mentor_request' | 'success_story';
          media_urls?: string[] | null;
          media_types?: string[] | null;
          media_captions?: string[] | null;
          tags?: string[] | null;
          categories?: string[] | null;
          university_tags?: string[] | null;
          program_tags?: string[] | null;
          visibility?: 'public' | 'private' | 'connections' | 'mentors';
          allowed_viewers?: string[] | null;
          comments_enabled?: boolean;
          sharing_enabled?: boolean;
          like_count?: number;
          comment_count?: number;
          share_count?: number;
          view_count?: number;
          is_flagged?: boolean;
          flag_reason?: string | null;
          is_approved?: boolean;
          moderated_by?: string | null;
          moderated_at?: string | null;
          is_scheduled?: boolean;
          scheduled_for?: string | null;
          is_pinned?: boolean;
          is_archived?: boolean;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          last_activity?: string;
        };
      };
      gradnet_likes: {
        Row: {
          id: string;
          user_id: string;
          post_id: string | null;
          comment_id: string | null;
          reaction_type: 'like' | 'love' | 'laugh' | 'celebrate' | 'insightful' | 'support';
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          post_id?: string | null;
          comment_id?: string | null;
          reaction_type?: 'like' | 'love' | 'laugh' | 'celebrate' | 'insightful' | 'support';
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          post_id?: string | null;
          comment_id?: string | null;
          reaction_type?: 'like' | 'love' | 'laugh' | 'celebrate' | 'insightful' | 'support';
          created_at?: string;
        };
      };
      gradnet_comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          parent_comment_id: string | null;
          content: string;
          media_url: string | null;
          like_count: number;
          reply_count: number;
          is_flagged: boolean;
          is_approved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          parent_comment_id?: string | null;
          content: string;
          media_url?: string | null;
          like_count?: number;
          reply_count?: number;
          is_flagged?: boolean;
          is_approved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string;
          parent_comment_id?: string | null;
          content?: string;
          media_url?: string | null;
          like_count?: number;
          reply_count?: number;
          is_flagged?: boolean;
          is_approved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      gradnet_connections: {
        Row: {
          id: string;
          requester_id: string;
          receiver_id: string;
          status: 'pending' | 'accepted' | 'declined' | 'blocked';
          connection_type: 'peer' | 'mentor' | 'mentee' | 'colleague' | 'alumni';
          request_message: string | null;
          response_message: string | null;
          mutual_connections: number;
          common_interests: string[] | null;
          common_universities: string[] | null;
          interaction_score: number;
          is_visible: boolean;
          requested_at: string;
          responded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          requester_id: string;
          receiver_id: string;
          status?: 'pending' | 'accepted' | 'declined' | 'blocked';
          connection_type?: 'peer' | 'mentor' | 'mentee' | 'colleague' | 'alumni';
          request_message?: string | null;
          response_message?: string | null;
          mutual_connections?: number;
          common_interests?: string[] | null;
          common_universities?: string[] | null;
          interaction_score?: number;
          is_visible?: boolean;
          requested_at?: string;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          requester_id?: string;
          receiver_id?: string;
          status?: 'pending' | 'accepted' | 'declined' | 'blocked';
          connection_type?: 'peer' | 'mentor' | 'mentee' | 'colleague' | 'alumni';
          request_message?: string | null;
          response_message?: string | null;
          mutual_connections?: number;
          common_interests?: string[] | null;
          common_universities?: string[] | null;
          interaction_score?: number;
          is_visible?: boolean;
          requested_at?: string;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          title: string | null;
          description: string | null;
          conversation_type: 'direct' | 'group' | 'support' | 'mentor_session';
          is_group: boolean;
          max_participants: number;
          admin_user_id: string | null;
          is_active: boolean;
          is_archived: boolean;
          is_muted: boolean;
          is_encrypted: boolean;
          visibility: 'public' | 'private' | 'connections';
          participant_count: number;
          message_count: number;
          last_message_at: string | null;
          last_activity: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          title?: string | null;
          description?: string | null;
          conversation_type?: 'direct' | 'group' | 'support' | 'mentor_session';
          is_group?: boolean;
          max_participants?: number;
          admin_user_id?: string | null;
          is_active?: boolean;
          is_archived?: boolean;
          is_muted?: boolean;
          is_encrypted?: boolean;
          visibility?: 'public' | 'private' | 'connections';
          participant_count?: number;
          message_count?: number;
          last_message_at?: string | null;
          last_activity?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string | null;
          description?: string | null;
          conversation_type?: 'direct' | 'group' | 'support' | 'mentor_session';
          is_group?: boolean;
          max_participants?: number;
          admin_user_id?: string | null;
          is_active?: boolean;
          is_archived?: boolean;
          is_muted?: boolean;
          is_encrypted?: boolean;
          visibility?: 'public' | 'private' | 'connections';
          participant_count?: number;
          message_count?: number;
          last_message_at?: string | null;
          last_activity?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          content: string | null;
          message_type: 'text' | 'image' | 'file' | 'audio' | 'video' | 'document' | 'link' | 'location' | 'contact' | 'voice_note';
          media_url: string | null;
          media_type: string | null;
          file_size: number | null;
          file_name: string | null;
          is_edited: boolean;
          edited_at: string | null;
          is_deleted: boolean;
          deleted_at: string | null;
          reply_to_message_id: string | null;
          is_system_message: boolean;
          delivery_status: 'sending' | 'sent' | 'delivered' | 'read' | 'failed';
          reaction_count: number;
          created_at: string;
          updated_at: string;
          delivered_at: string | null;
          read_at: string | null;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          content?: string | null;
          message_type?: 'text' | 'image' | 'file' | 'audio' | 'video' | 'document' | 'link' | 'location' | 'contact' | 'voice_note';
          media_url?: string | null;
          media_type?: string | null;
          file_size?: number | null;
          file_name?: string | null;
          is_edited?: boolean;
          edited_at?: string | null;
          is_deleted?: boolean;
          deleted_at?: string | null;
          reply_to_message_id?: string | null;
          is_system_message?: boolean;
          delivery_status?: 'sending' | 'sent' | 'delivered' | 'read' | 'failed';
          reaction_count?: number;
          created_at?: string;
          updated_at?: string;
          delivered_at?: string | null;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          content?: string | null;
          message_type?: 'text' | 'image' | 'file' | 'audio' | 'video' | 'document' | 'link' | 'location' | 'contact' | 'voice_note';
          media_url?: string | null;
          media_type?: string | null;
          file_size?: number | null;
          file_name?: string | null;
          is_edited?: boolean;
          edited_at?: string | null;
          is_deleted?: boolean;
          deleted_at?: string | null;
          reply_to_message_id?: string | null;
          is_system_message?: boolean;
          delivery_status?: 'sending' | 'sent' | 'delivered' | 'read' | 'failed';
          reaction_count?: number;
          created_at?: string;
          updated_at?: string;
          delivered_at?: string | null;
          read_at?: string | null;
        };
      };
      academic_profiles: {
        Row: {
          id: string;
          user_id: string;
          current_degree: string | null;
          current_institution: string | null;
          current_field_of_study: string | null;
          current_gpa: number | null;
          current_cgpa: number | null;
          graduation_year: number | null;
          graduation_month: number | null;
          expected_graduation: string | null;
          previous_education: any[] | null;
          honors_awards: string[] | null;
          scholarships: string[] | null;
          dean_list_semesters: string[] | null;
          publications: string[] | null;
          conferences_attended: string[] | null;
          presentations_given: string[] | null;
          research_experience: string | null;
          work_experience: string | null;
          internships: string[] | null;
          volunteer_experience: string | null;
          leadership_experience: string | null;
          certifications: string[] | null;
          professional_memberships: string[] | null;
          gre_verbal: number | null;
          gre_quantitative: number | null;
          gre_analytical: number | null;
          gre_date: string | null;
          gmat_score: number | null;
          gmat_date: string | null;
          toefl_score: number | null;
          toefl_date: string | null;
          ielts_score: number | null;
          ielts_date: string | null;
          duolingo_score: number | null;
          duolingo_date: string | null;
          technical_skills: string[] | null;
          soft_skills: string[] | null;
          programming_languages: string[] | null;
          tools_and_technologies: string[] | null;
          languages: any[] | null;
          research_interests: string[] | null;
          career_goals: string | null;
          target_industries: string[] | null;
          preferred_work_locations: string[] | null;
          reference_contacts: any[] | null;
          profile_strength_score: number;
          last_cv_upload: string | null;
          cv_analysis_score: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          current_degree?: string | null;
          current_institution?: string | null;
          current_field_of_study?: string | null;
          current_gpa?: number | null;
          current_cgpa?: number | null;
          graduation_year?: number | null;
          graduation_month?: number | null;
          expected_graduation?: string | null;
          previous_education?: any[] | null;
          honors_awards?: string[] | null;
          scholarships?: string[] | null;
          dean_list_semesters?: string[] | null;
          publications?: string[] | null;
          conferences_attended?: string[] | null;
          presentations_given?: string[] | null;
          research_experience?: string | null;
          work_experience?: string | null;
          internships?: string[] | null;
          volunteer_experience?: string | null;
          leadership_experience?: string | null;
          certifications?: string[] | null;
          professional_memberships?: string[] | null;
          gre_verbal?: number | null;
          gre_quantitative?: number | null;
          gre_analytical?: number | null;
          gre_date?: string | null;
          gmat_score?: number | null;
          gmat_date?: string | null;
          toefl_score?: number | null;
          toefl_date?: string | null;
          ielts_score?: number | null;
          ielts_date?: string | null;
          duolingo_score?: number | null;
          duolingo_date?: string | null;
          technical_skills?: string[] | null;
          soft_skills?: string[] | null;
          programming_languages?: string[] | null;
          tools_and_technologies?: string[] | null;
          languages?: any[] | null;
          research_interests?: string[] | null;
          career_goals?: string | null;
          target_industries?: string[] | null;
          preferred_work_locations?: string[] | null;
          reference_contacts?: any[] | null;
          profile_strength_score?: number;
          last_cv_upload?: string | null;
          cv_analysis_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          current_degree?: string | null;
          current_institution?: string | null;
          current_field_of_study?: string | null;
          current_gpa?: number | null;
          current_cgpa?: number | null;
          graduation_year?: number | null;
          graduation_month?: number | null;
          expected_graduation?: string | null;
          previous_education?: any[] | null;
          honors_awards?: string[] | null;
          scholarships?: string[] | null;
          dean_list_semesters?: string[] | null;
          publications?: string[] | null;
          conferences_attended?: string[] | null;
          presentations_given?: string[] | null;
          research_experience?: string | null;
          work_experience?: string | null;
          internships?: string[] | null;
          volunteer_experience?: string | null;
          leadership_experience?: string | null;
          certifications?: string[] | null;
          professional_memberships?: string[] | null;
          gre_verbal?: number | null;
          gre_quantitative?: number | null;
          gre_analytical?: number | null;
          gre_date?: string | null;
          gmat_score?: number | null;
          gmat_date?: string | null;
          toefl_score?: number | null;
          toefl_date?: string | null;
          ielts_score?: number | null;
          ielts_date?: string | null;
          duolingo_score?: number | null;
          duolingo_date?: string | null;
          technical_skills?: string[] | null;
          soft_skills?: string[] | null;
          programming_languages?: string[] | null;
          tools_and_technologies?: string[] | null;
          languages?: any[] | null;
          research_interests?: string[] | null;
          career_goals?: string | null;
          target_industries?: string[] | null;
          preferred_work_locations?: string[] | null;
          reference_contacts?: any[] | null;
          profile_strength_score?: number;
          last_cv_upload?: string | null;
          cv_analysis_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      mentor_sessions: {
        Row: {
          id: string;
          mentor_id: string;
          mentee_id: string;
          session_type: string;
          scheduled_at: string;
          duration_minutes: number;
          meeting_link: string | null;
          calendar_event_id: string | null;
          zoom_meeting_id: string | null;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          session_notes: string | null;
          mentor_feedback: string | null;
          mentee_feedback: string | null;
          rating: number | null;
          amount_paid: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          mentor_id: string;
          mentee_id: string;
          session_type?: string;
          scheduled_at: string;
          duration_minutes?: number;
          meeting_link?: string | null;
          calendar_event_id?: string | null;
          zoom_meeting_id?: string | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          session_notes?: string | null;
          mentor_feedback?: string | null;
          mentee_feedback?: string | null;
          rating?: number | null;
          amount_paid?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          mentor_id?: string;
          mentee_id?: string;
          session_type?: string;
          scheduled_at?: string;
          duration_minutes?: number;
          meeting_link?: string | null;
          calendar_event_id?: string | null;
          zoom_meeting_id?: string | null;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          session_notes?: string | null;
          mentor_feedback?: string | null;
          mentee_feedback?: string | null;
          rating?: number | null;
          amount_paid?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Functions: {
      get_trending_hashtags: {
        Args: { tag_limit?: number };
        Returns: { tag: string; count: number }[];
      };
      get_unread_message_count: {
        Args: { user_id: string };
        Returns: number;
      };
    };
    Enums: {
      user_role: 'applicant' | 'mentor' | 'admin' | 'university_rep' | 'consultant' | 'super_admin';
      connection_status: 'pending' | 'accepted' | 'declined' | 'blocked';
      connection_type: 'peer' | 'mentor' | 'mentee' | 'colleague' | 'alumni';
      post_type: 'general' | 'question' | 'resource' | 'achievement' | 'announcement' | 'discussion' | 'job_posting' | 'study_group' | 'mentor_request' | 'success_story';
      post_visibility: 'public' | 'private' | 'connections' | 'mentors';
      visibility_level: 'public' | 'private' | 'connections';
      interaction_type: 'like' | 'love' | 'laugh' | 'celebrate' | 'insightful' | 'support';
      message_type: 'text' | 'image' | 'file' | 'audio' | 'video' | 'document' | 'link' | 'location' | 'contact' | 'voice_note';
      session_status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
      verification_status: 'unverified' | 'pending' | 'verified' | 'rejected';
      priority_level: 'low' | 'medium' | 'high';
      notification_type: 'email' | 'push' | 'sms' | 'in_app';
      application_status: 'not_started' | 'in_progress' | 'submitted' | 'under_review' | 'accepted' | 'rejected' | 'waitlisted' | 'deferred';
      document_status: 'draft' | 'in_review' | 'approved' | 'needs_revision' | 'published' | 'archived';
      processing_status: 'pending' | 'processing' | 'completed' | 'failed';
      cv_processing_status: 'pending' | 'processing' | 'completed' | 'failed';
      scraping_status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'cancelled';
      country: 'US' | 'UK' | 'CA' | 'AU' | 'DE' | 'FR' | 'NL' | 'SE' | 'NO' | 'DK' | 'SG' | 'JP' | 'KR' | 'CN' | 'IN' | 'BR' | 'MX' | 'AR' | 'ZA' | 'EG' | 'NG' | 'KE' | 'GH' | 'ET' | 'MA' | 'TN' | 'DZ' | 'LY' | 'SD' | 'UG' | 'TZ' | 'ZW' | 'ZM' | 'MW' | 'BW' | 'NA' | 'SZ' | 'LS' | 'MG' | 'MU' | 'SC' | 'CV' | 'ST' | 'GQ' | 'GA' | 'CF' | 'TD' | 'CM' | 'NE' | 'ML' | 'BF' | 'CI' | 'LR' | 'SL' | 'GN' | 'GW' | 'SN' | 'GM' | 'MR';
    };
  };
}